// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (household_id, name, account_type, currency_code, created_by, updated_by)
VALUES ($1, $2, $3,
        $4, $5, $6)
RETURNING id, household_id, name, account_type, currency_code, balance, status, version,
          created_at, updated_at, created_by, updated_by
`

type CreateAccountParams struct {
	HouseholdID  uuid.UUID   `json:"household_id"`
	Name         string      `json:"name"`
	AccountType  string      `json:"account_type"`
	CurrencyCode string      `json:"currency_code"`
	CreatedBy    pgtype.UUID `json:"created_by"`
	UpdatedBy    pgtype.UUID `json:"updated_by"`
}

type CreateAccountRow struct {
	ID           uuid.UUID          `json:"id"`
	HouseholdID  uuid.UUID          `json:"household_id"`
	Name         string             `json:"name"`
	AccountType  string             `json:"account_type"`
	CurrencyCode string             `json:"currency_code"`
	Balance      int64              `json:"balance"`
	Status       string             `json:"status"`
	Version      int32              `json:"version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	UpdatedBy    pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.HouseholdID,
		arg.Name,
		arg.AccountType,
		arg.CurrencyCode,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.AccountType,
		&i.CurrencyCode,
		&i.Balance,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deactivateAccount = `-- name: DeactivateAccount :exec
UPDATE accounts
SET deleted_at = NOW(),
    updated_at = NOW(),
    updated_by = $1,
    status     = 'INACTIVE'
WHERE id       = $2
  AND deleted_at IS NULL
`

type DeactivateAccountParams struct {
	UpdatedBy pgtype.UUID `json:"updated_by"`
	ID        uuid.UUID   `json:"id"`
}

func (q *Queries) DeactivateAccount(ctx context.Context, arg DeactivateAccountParams) error {
	_, err := q.db.Exec(ctx, deactivateAccount, arg.UpdatedBy, arg.ID)
	return err
}

const findAccountByID = `-- name: FindAccountByID :one
SELECT id, household_id, name, account_type, currency_code, balance, status, version,
       created_at, updated_at, created_by, updated_by
FROM accounts
WHERE id = $1
  AND deleted_at IS NULL
`

type FindAccountByIDRow struct {
	ID           uuid.UUID          `json:"id"`
	HouseholdID  uuid.UUID          `json:"household_id"`
	Name         string             `json:"name"`
	AccountType  string             `json:"account_type"`
	CurrencyCode string             `json:"currency_code"`
	Balance      int64              `json:"balance"`
	Status       string             `json:"status"`
	Version      int32              `json:"version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	UpdatedBy    pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) FindAccountByID(ctx context.Context, id uuid.UUID) (FindAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, findAccountByID, id)
	var i FindAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.AccountType,
		&i.CurrencyCode,
		&i.Balance,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listAccountsForHousehold = `-- name: ListAccountsForHousehold :many
SELECT id, household_id, name, account_type, currency_code, balance, status, version,
       created_at, updated_at, created_by, updated_by
FROM accounts
WHERE household_id = $1
  AND deleted_at IS NULL
ORDER BY name
`

type ListAccountsForHouseholdRow struct {
	ID           uuid.UUID          `json:"id"`
	HouseholdID  uuid.UUID          `json:"household_id"`
	Name         string             `json:"name"`
	AccountType  string             `json:"account_type"`
	CurrencyCode string             `json:"currency_code"`
	Balance      int64              `json:"balance"`
	Status       string             `json:"status"`
	Version      int32              `json:"version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	UpdatedBy    pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) ListAccountsForHousehold(ctx context.Context, householdID uuid.UUID) ([]ListAccountsForHouseholdRow, error) {
	rows, err := q.db.Query(ctx, listAccountsForHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsForHouseholdRow
	for rows.Next() {
		var i ListAccountsForHouseholdRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.AccountType,
			&i.CurrencyCode,
			&i.Balance,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE accounts
SET balance    = $1,
    updated_at = NOW(),
    updated_by = $2,
    version    = version + 1
WHERE id       = $3
  AND version  = $4
  AND deleted_at IS NULL
RETURNING id, household_id, name, account_type, currency_code, balance, status, version,
          created_at, updated_at, created_by, updated_by
`

type UpdateAccountBalanceParams struct {
	Balance         int64       `json:"balance"`
	UpdatedBy       pgtype.UUID `json:"updated_by"`
	ID              uuid.UUID   `json:"id"`
	ExpectedVersion int32       `json:"expected_version"`
}

type UpdateAccountBalanceRow struct {
	ID           uuid.UUID          `json:"id"`
	HouseholdID  uuid.UUID          `json:"household_id"`
	Name         string             `json:"name"`
	AccountType  string             `json:"account_type"`
	CurrencyCode string             `json:"currency_code"`
	Balance      int64              `json:"balance"`
	Status       string             `json:"status"`
	Version      int32              `json:"version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	UpdatedBy    pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (UpdateAccountBalanceRow, error) {
	row := q.db.QueryRow(ctx, updateAccountBalance,
		arg.Balance,
		arg.UpdatedBy,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i UpdateAccountBalanceRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.AccountType,
		&i.CurrencyCode,
		&i.Balance,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateAccountName = `-- name: UpdateAccountName :one
UPDATE accounts
SET name       = $1,
    updated_at = NOW(),
    updated_by = $2,
    version    = version + 1
WHERE id       = $3
  AND version  = $4
  AND deleted_at IS NULL
RETURNING id, household_id, name, account_type, currency_code, balance, status, version,
          created_at, updated_at, created_by, updated_by
`

type UpdateAccountNameParams struct {
	Name            string      `json:"name"`
	UpdatedBy       pgtype.UUID `json:"updated_by"`
	ID              uuid.UUID   `json:"id"`
	ExpectedVersion int32       `json:"expected_version"`
}

type UpdateAccountNameRow struct {
	ID           uuid.UUID          `json:"id"`
	HouseholdID  uuid.UUID          `json:"household_id"`
	Name         string             `json:"name"`
	AccountType  string             `json:"account_type"`
	CurrencyCode string             `json:"currency_code"`
	Balance      int64              `json:"balance"`
	Status       string             `json:"status"`
	Version      int32              `json:"version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	UpdatedBy    pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) UpdateAccountName(ctx context.Context, arg UpdateAccountNameParams) (UpdateAccountNameRow, error) {
	row := q.db.QueryRow(ctx, updateAccountName,
		arg.Name,
		arg.UpdatedBy,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i UpdateAccountNameRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.AccountType,
		&i.CurrencyCode,
		&i.Balance,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
