// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credit_card_settings.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCreditCardSettings = `-- name: CreateCreditCardSettings :one
INSERT INTO credit_card_settings (account_id, closing_day, due_day, limit_amount, created_by, updated_by)
VALUES ($1, $2, $3,
        $4, $5, $6)
RETURNING id, account_id, closing_day, due_day, limit_amount, version,
          created_at, updated_at, created_by, updated_by
`

type CreateCreditCardSettingsParams struct {
	AccountID   uuid.UUID   `json:"account_id"`
	ClosingDay  int32       `json:"closing_day"`
	DueDay      int32       `json:"due_day"`
	LimitAmount int64       `json:"limit_amount"`
	CreatedBy   pgtype.UUID `json:"created_by"`
	UpdatedBy   pgtype.UUID `json:"updated_by"`
}

type CreateCreditCardSettingsRow struct {
	ID          uuid.UUID          `json:"id"`
	AccountID   uuid.UUID          `json:"account_id"`
	ClosingDay  int32              `json:"closing_day"`
	DueDay      int32              `json:"due_day"`
	LimitAmount int64              `json:"limit_amount"`
	Version     int32              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) CreateCreditCardSettings(ctx context.Context, arg CreateCreditCardSettingsParams) (CreateCreditCardSettingsRow, error) {
	row := q.db.QueryRow(ctx, createCreditCardSettings,
		arg.AccountID,
		arg.ClosingDay,
		arg.DueDay,
		arg.LimitAmount,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i CreateCreditCardSettingsRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ClosingDay,
		&i.DueDay,
		&i.LimitAmount,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteCreditCardSettings = `-- name: DeleteCreditCardSettings :exec
UPDATE credit_card_settings
SET deleted_at = NOW(),
    updated_at = NOW(),
    updated_by = $1
WHERE account_id = $2
  AND deleted_at IS NULL
`

type DeleteCreditCardSettingsParams struct {
	UpdatedBy pgtype.UUID `json:"updated_by"`
	AccountID uuid.UUID   `json:"account_id"`
}

func (q *Queries) DeleteCreditCardSettings(ctx context.Context, arg DeleteCreditCardSettingsParams) error {
	_, err := q.db.Exec(ctx, deleteCreditCardSettings, arg.UpdatedBy, arg.AccountID)
	return err
}

const findCreditCardSettingsByAccountID = `-- name: FindCreditCardSettingsByAccountID :one
SELECT id, account_id, closing_day, due_day, limit_amount, version,
       created_at, updated_at, created_by, updated_by
FROM credit_card_settings
WHERE account_id = $1
  AND deleted_at IS NULL
`

type FindCreditCardSettingsByAccountIDRow struct {
	ID          uuid.UUID          `json:"id"`
	AccountID   uuid.UUID          `json:"account_id"`
	ClosingDay  int32              `json:"closing_day"`
	DueDay      int32              `json:"due_day"`
	LimitAmount int64              `json:"limit_amount"`
	Version     int32              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) FindCreditCardSettingsByAccountID(ctx context.Context, accountID uuid.UUID) (FindCreditCardSettingsByAccountIDRow, error) {
	row := q.db.QueryRow(ctx, findCreditCardSettingsByAccountID, accountID)
	var i FindCreditCardSettingsByAccountIDRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ClosingDay,
		&i.DueDay,
		&i.LimitAmount,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateCreditCardClosingDay = `-- name: UpdateCreditCardClosingDay :one
UPDATE credit_card_settings
SET closing_day = $1,
    updated_at  = NOW(),
    updated_by  = $2,
    version     = version + 1
WHERE account_id = $3
  AND version    = $4
  AND deleted_at IS NULL
RETURNING id, account_id, closing_day, due_day, limit_amount, version,
          created_at, updated_at, created_by, updated_by
`

type UpdateCreditCardClosingDayParams struct {
	ClosingDay      int32       `json:"closing_day"`
	UpdatedBy       pgtype.UUID `json:"updated_by"`
	AccountID       uuid.UUID   `json:"account_id"`
	ExpectedVersion int32       `json:"expected_version"`
}

type UpdateCreditCardClosingDayRow struct {
	ID          uuid.UUID          `json:"id"`
	AccountID   uuid.UUID          `json:"account_id"`
	ClosingDay  int32              `json:"closing_day"`
	DueDay      int32              `json:"due_day"`
	LimitAmount int64              `json:"limit_amount"`
	Version     int32              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) UpdateCreditCardClosingDay(ctx context.Context, arg UpdateCreditCardClosingDayParams) (UpdateCreditCardClosingDayRow, error) {
	row := q.db.QueryRow(ctx, updateCreditCardClosingDay,
		arg.ClosingDay,
		arg.UpdatedBy,
		arg.AccountID,
		arg.ExpectedVersion,
	)
	var i UpdateCreditCardClosingDayRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ClosingDay,
		&i.DueDay,
		&i.LimitAmount,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateCreditCardDueDay = `-- name: UpdateCreditCardDueDay :one
UPDATE credit_card_settings
SET due_day    = $1,
    updated_at = NOW(),
    updated_by = $2,
    version    = version + 1
WHERE account_id = $3
  AND version    = $4
  AND deleted_at IS NULL
RETURNING id, account_id, closing_day, due_day, limit_amount, version,
          created_at, updated_at, created_by, updated_by
`

type UpdateCreditCardDueDayParams struct {
	DueDay          int32       `json:"due_day"`
	UpdatedBy       pgtype.UUID `json:"updated_by"`
	AccountID       uuid.UUID   `json:"account_id"`
	ExpectedVersion int32       `json:"expected_version"`
}

type UpdateCreditCardDueDayRow struct {
	ID          uuid.UUID          `json:"id"`
	AccountID   uuid.UUID          `json:"account_id"`
	ClosingDay  int32              `json:"closing_day"`
	DueDay      int32              `json:"due_day"`
	LimitAmount int64              `json:"limit_amount"`
	Version     int32              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) UpdateCreditCardDueDay(ctx context.Context, arg UpdateCreditCardDueDayParams) (UpdateCreditCardDueDayRow, error) {
	row := q.db.QueryRow(ctx, updateCreditCardDueDay,
		arg.DueDay,
		arg.UpdatedBy,
		arg.AccountID,
		arg.ExpectedVersion,
	)
	var i UpdateCreditCardDueDayRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ClosingDay,
		&i.DueDay,
		&i.LimitAmount,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateCreditCardLimit = `-- name: UpdateCreditCardLimit :one
UPDATE credit_card_settings
SET limit_amount = $1,
    updated_at   = NOW(),
    updated_by   = $2,
    version      = version + 1
WHERE account_id = $3
  AND version    = $4
  AND deleted_at IS NULL
RETURNING id, account_id, closing_day, due_day, limit_amount, version,
          created_at, updated_at, created_by, updated_by
`

type UpdateCreditCardLimitParams struct {
	LimitAmount     int64       `json:"limit_amount"`
	UpdatedBy       pgtype.UUID `json:"updated_by"`
	AccountID       uuid.UUID   `json:"account_id"`
	ExpectedVersion int32       `json:"expected_version"`
}

type UpdateCreditCardLimitRow struct {
	ID          uuid.UUID          `json:"id"`
	AccountID   uuid.UUID          `json:"account_id"`
	ClosingDay  int32              `json:"closing_day"`
	DueDay      int32              `json:"due_day"`
	LimitAmount int64              `json:"limit_amount"`
	Version     int32              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) UpdateCreditCardLimit(ctx context.Context, arg UpdateCreditCardLimitParams) (UpdateCreditCardLimitRow, error) {
	row := q.db.QueryRow(ctx, updateCreditCardLimit,
		arg.LimitAmount,
		arg.UpdatedBy,
		arg.AccountID,
		arg.ExpectedVersion,
	)
	var i UpdateCreditCardLimitRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ClosingDay,
		&i.DueDay,
		&i.LimitAmount,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
