// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: households.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createHousehold = `-- name: CreateHousehold :one
INSERT INTO households (name, created_by, updated_by)
VALUES ($1, $2, $3)
RETURNING id, name, status, version, created_at, updated_at, created_by, updated_by
`

type CreateHouseholdParams struct {
	Name      string      `json:"name"`
	CreatedBy pgtype.UUID `json:"created_by"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

type CreateHouseholdRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (CreateHouseholdRow, error) {
	row := q.db.QueryRow(ctx, createHousehold, arg.Name, arg.CreatedBy, arg.UpdatedBy)
	var i CreateHouseholdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const createHouseholdMember = `-- name: CreateHouseholdMember :one
INSERT INTO household_members (household_id, user_id, role, invited_by)
VALUES ($1, $2, $3, $4)
RETURNING household_id, user_id, role, invited_by, joined_at
`

type CreateHouseholdMemberParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	UserID      uuid.UUID   `json:"user_id"`
	Role        string      `json:"role"`
	InvitedBy   pgtype.UUID `json:"invited_by"`
}

type CreateHouseholdMemberRow struct {
	HouseholdID uuid.UUID          `json:"household_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	InvitedBy   pgtype.UUID        `json:"invited_by"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) CreateHouseholdMember(ctx context.Context, arg CreateHouseholdMemberParams) (CreateHouseholdMemberRow, error) {
	row := q.db.QueryRow(ctx, createHouseholdMember,
		arg.HouseholdID,
		arg.UserID,
		arg.Role,
		arg.InvitedBy,
	)
	var i CreateHouseholdMemberRow
	err := row.Scan(
		&i.HouseholdID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
	)
	return i, err
}

const deactivateHousehold = `-- name: DeactivateHousehold :exec
UPDATE households
SET deleted_at = NOW(),
    updated_at = NOW(),
    updated_by = $1,
    status     = 'INACTIVE'
WHERE id       = $2
  AND deleted_at IS NULL
`

type DeactivateHouseholdParams struct {
	UpdatedBy pgtype.UUID `json:"updated_by"`
	ID        uuid.UUID   `json:"id"`
}

func (q *Queries) DeactivateHousehold(ctx context.Context, arg DeactivateHouseholdParams) error {
	_, err := q.db.Exec(ctx, deactivateHousehold, arg.UpdatedBy, arg.ID)
	return err
}

const findHouseholdByID = `-- name: FindHouseholdByID :one
SELECT id, name, status, version, created_at, updated_at, created_by, updated_by
FROM households
WHERE id = $1
  AND deleted_at IS NULL
`

type FindHouseholdByIDRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) FindHouseholdByID(ctx context.Context, id uuid.UUID) (FindHouseholdByIDRow, error) {
	row := q.db.QueryRow(ctx, findHouseholdByID, id)
	var i FindHouseholdByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const findMembership = `-- name: FindMembership :one
SELECT household_id, user_id, role, invited_by, joined_at
FROM household_members
WHERE household_id = $1
  AND user_id      = $2
  AND deleted_at IS NULL
`

type FindMembershipParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
}

type FindMembershipRow struct {
	HouseholdID uuid.UUID          `json:"household_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	InvitedBy   pgtype.UUID        `json:"invited_by"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) FindMembership(ctx context.Context, arg FindMembershipParams) (FindMembershipRow, error) {
	row := q.db.QueryRow(ctx, findMembership, arg.HouseholdID, arg.UserID)
	var i FindMembershipRow
	err := row.Scan(
		&i.HouseholdID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
	)
	return i, err
}

const listHouseholdsForUser = `-- name: ListHouseholdsForUser :many
SELECT h.id, h.name, h.status, h.version, h.created_at, h.updated_at, h.created_by, h.updated_by
FROM households h
JOIN household_members hm ON hm.household_id = h.id
WHERE hm.user_id = $1
  AND hm.deleted_at IS NULL
  AND h.deleted_at IS NULL
`

type ListHouseholdsForUserRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) ListHouseholdsForUser(ctx context.Context, userID uuid.UUID) ([]ListHouseholdsForUserRow, error) {
	rows, err := q.db.Query(ctx, listHouseholdsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHouseholdsForUserRow
	for rows.Next() {
		var i ListHouseholdsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT household_id, user_id, role, invited_by, joined_at
FROM household_members
WHERE household_id = $1
  AND deleted_at IS NULL
`

type ListMembersRow struct {
	HouseholdID uuid.UUID          `json:"household_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	InvitedBy   pgtype.UUID        `json:"invited_by"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ListMembers(ctx context.Context, householdID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.HouseholdID,
			&i.UserID,
			&i.Role,
			&i.InvitedBy,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeHouseholdMember = `-- name: RemoveHouseholdMember :exec
UPDATE household_members
SET deleted_at = NOW()
WHERE household_id = $1
  AND user_id      = $2
  AND deleted_at IS NULL
`

type RemoveHouseholdMemberParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveHouseholdMember(ctx context.Context, arg RemoveHouseholdMemberParams) error {
	_, err := q.db.Exec(ctx, removeHouseholdMember, arg.HouseholdID, arg.UserID)
	return err
}

const updateHouseholdName = `-- name: UpdateHouseholdName :one
UPDATE households
SET name       = $1,
    updated_at = NOW(),
    updated_by = $2,
    version    = version + 1
WHERE id       = $3
  AND version  = $4
  AND deleted_at IS NULL
RETURNING id, name, status, version, created_at, updated_at, created_by, updated_by
`

type UpdateHouseholdNameParams struct {
	Name            string      `json:"name"`
	UpdatedBy       pgtype.UUID `json:"updated_by"`
	ID              uuid.UUID   `json:"id"`
	ExpectedVersion int32       `json:"expected_version"`
}

type UpdateHouseholdNameRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) UpdateHouseholdName(ctx context.Context, arg UpdateHouseholdNameParams) (UpdateHouseholdNameRow, error) {
	row := q.db.QueryRow(ctx, updateHouseholdName,
		arg.Name,
		arg.UpdatedBy,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i UpdateHouseholdNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
