// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adjustAccountBalance = `-- name: AdjustAccountBalance :exec
UPDATE accounts
SET balance    = balance + $1,
    updated_at = NOW(),
    version    = version + 1
WHERE id       = $2
  AND deleted_at IS NULL
`

type AdjustAccountBalanceParams struct {
	Delta int64     `json:"delta"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) AdjustAccountBalance(ctx context.Context, arg AdjustAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, adjustAccountBalance, arg.Delta, arg.ID)
	return err
}

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT balance
FROM accounts
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetAccountBalance(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getAccountBalance, id)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :one
INSERT INTO ledger_entries (transaction_id, account_id, entry_type, amount)
VALUES ($1, $2,
        $3, $4)
RETURNING id, transaction_id, account_id, entry_type, amount, created_at
`

type InsertLedgerEntryParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	AccountID     uuid.UUID `json:"account_id"`
	EntryType     string    `json:"entry_type"`
	Amount        int64     `json:"amount"`
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, insertLedgerEntry,
		arg.TransactionID,
		arg.AccountID,
		arg.EntryType,
		arg.Amount,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.AccountID,
		&i.EntryType,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (household_id, description, transaction_date, created_by)
VALUES ($1, $2,
        $3, $4)
RETURNING id, household_id, description, transaction_date, created_at, created_by
`

type InsertTransactionParams struct {
	HouseholdID     uuid.UUID   `json:"household_id"`
	Description     string      `json:"description"`
	TransactionDate pgtype.Date `json:"transaction_date"`
	CreatedBy       pgtype.UUID `json:"created_by"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.HouseholdID,
		arg.Description,
		arg.TransactionDate,
		arg.CreatedBy,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Description,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listEntriesForTransaction = `-- name: ListEntriesForTransaction :many
SELECT id, transaction_id, account_id, entry_type, amount, created_at
FROM ledger_entries
WHERE transaction_id = $1
ORDER BY created_at
`

func (q *Queries) ListEntriesForTransaction(ctx context.Context, transactionID uuid.UUID) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listEntriesForTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.EntryType,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionIDsForAccount = `-- name: ListTransactionIDsForAccount :many
SELECT DISTINCT transaction_id
FROM ledger_entries
WHERE account_id = $1
ORDER BY transaction_id
`

func (q *Queries) ListTransactionIDsForAccount(ctx context.Context, accountID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listTransactionIDsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var transaction_id uuid.UUID
		if err := rows.Scan(&transaction_id); err != nil {
			return nil, err
		}
		items = append(items, transaction_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsForHousehold = `-- name: ListTransactionsForHousehold :many
SELECT id, household_id, description, transaction_date, created_at, created_by
FROM transactions
WHERE household_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListTransactionsForHouseholdParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	QueryOffset int32     `json:"query_offset"`
	QueryLimit  int32     `json:"query_limit"`
}

func (q *Queries) ListTransactionsForHousehold(ctx context.Context, arg ListTransactionsForHouseholdParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsForHousehold, arg.HouseholdID, arg.QueryOffset, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Description,
			&i.TransactionDate,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
