// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT
    id,
    email,
    password_hash,
    deleted_at
FROM users
WHERE lower(email) = lower($1)
  AND deleted_at IS NULL
LIMIT 1
`

type FindUserByEmailRow struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i FindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DeletedAt,
	)
	return i, err
}
