//go:build integration

package database

import (
	"context"
	"testing"

	"github.com/pressly/goose/v3"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestCreditCardSettingsMigration_ReferencesOneAccount verifies AC1: credit card settings
// reference exactly one account via account_id FK.
func TestCreditCardSettingsMigration_ReferencesOneAccount(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	db := newTestDB(t, ctx)
	require.NoError(t, Migrate(ctx, db, usersMigrationsFS(t)))

	var userID, householdID, accountID string
	err := db.QueryRowContext(ctx,
		"INSERT INTO users (email, password_hash, display_name) VALUES ($1, $2, $3) RETURNING id::text",
		"alice@example.com", testPasswordHash, "Alice",
	).Scan(&userID)
	require.NoError(t, err)

	err = db.QueryRowContext(ctx,
		"INSERT INTO households (name, created_by, updated_by) VALUES ($1, $2::uuid, $2::uuid) RETURNING id::text",
		"Personal", userID,
	).Scan(&householdID)
	require.NoError(t, err)

	err = db.QueryRowContext(ctx,
		"INSERT INTO accounts (household_id, name, account_type, currency_code, created_by, updated_by) VALUES ($1::uuid, $2, $3, $4, $5::uuid, $5::uuid) RETURNING id::text",
		householdID, "My Credit Card", "CREDIT_CARD", "USD", userID,
	).Scan(&accountID)
	require.NoError(t, err)

	var settingsID string
	err = db.QueryRowContext(ctx,
		`INSERT INTO credit_card_settings (account_id, closing_day, due_day, limit_amount, created_by, updated_by)
		 VALUES ($1::uuid, $2, $3, $4, $5::uuid, $5::uuid) RETURNING id::text`,
		accountID, 15, 25, 500000, userID,
	).Scan(&settingsID)

	require.NoError(t, err)
	assert.NotEmpty(t, settingsID, "credit card settings id must be generated by the database")
}

// TestCreditCardSettingsMigration_UniquePerAccount verifies AC2: a second set of settings
// for the same account is rejected by the unique constraint on account_id.
func TestCreditCardSettingsMigration_UniquePerAccount(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	db := newTestDB(t, ctx)
	require.NoError(t, Migrate(ctx, db, usersMigrationsFS(t)))

	var userID, householdID, accountID string
	err := db.QueryRowContext(ctx,
		"INSERT INTO users (email, password_hash, display_name) VALUES ($1, $2, $3) RETURNING id::text",
		"bob@example.com", testPasswordHash, "Bob",
	).Scan(&userID)
	require.NoError(t, err)

	err = db.QueryRowContext(ctx,
		"INSERT INTO households (name, created_by, updated_by) VALUES ($1, $2::uuid, $2::uuid) RETURNING id::text",
		"Bob's Household", userID,
	).Scan(&householdID)
	require.NoError(t, err)

	err = db.QueryRowContext(ctx,
		"INSERT INTO accounts (household_id, name, account_type, currency_code, created_by, updated_by) VALUES ($1::uuid, $2, $3, $4, $5::uuid, $5::uuid) RETURNING id::text",
		householdID, "Visa", "CREDIT_CARD", "BRL", userID,
	).Scan(&accountID)
	require.NoError(t, err)

	_, err = db.ExecContext(ctx,
		"INSERT INTO credit_card_settings (account_id, closing_day, due_day, limit_amount, created_by, updated_by) VALUES ($1::uuid, $2, $3, $4, $5::uuid, $5::uuid)",
		accountID, 10, 20, 200000, userID,
	)
	require.NoError(t, err)

	_, err = db.ExecContext(ctx,
		"INSERT INTO credit_card_settings (account_id, closing_day, due_day, limit_amount, created_by, updated_by) VALUES ($1::uuid, $2, $3, $4, $5::uuid, $5::uuid)",
		accountID, 5, 15, 300000, userID,
	)
	assert.Error(t, err, "second settings row for same account must be rejected")
}

// TestCreditCardSettingsMigration_ClosingDayRange verifies AC3 + EC1: closing_day must be
// between 1 and 31 inclusive. Tests boundary violations at 0 and 32.
func TestCreditCardSettingsMigration_ClosingDayRange(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	db := newTestDB(t, ctx)
	require.NoError(t, Migrate(ctx, db, usersMigrationsFS(t)))

	var userID, householdID, accountID string
	err := db.QueryRowContext(ctx,
		"INSERT INTO users (email, password_hash, display_name) VALUES ($1, $2, $3) RETURNING id::text",
		"carol@example.com", testPasswordHash, "Carol",
	).Scan(&userID)
	require.NoError(t, err)

	err = db.QueryRowContext(ctx,
		"INSERT INTO households (name, created_by, updated_by) VALUES ($1, $2::uuid, $2::uuid) RETURNING id::text",
		"Carol's Household", userID,
	).Scan(&householdID)
	require.NoError(t, err)

	err = db.QueryRowContext(ctx,
		"INSERT INTO accounts (household_id, name, account_type, currency_code, created_by, updated_by) VALUES ($1::uuid, $2, $3, $4, $5::uuid, $5::uuid) RETURNING id::text",
		householdID, "Mastercard", "CREDIT_CARD", "EUR", userID,
	).Scan(&accountID)
	require.NoError(t, err)

	// day=0 must be rejected.
	_, err = db.ExecContext(ctx,
		"INSERT INTO credit_card_settings (account_id, closing_day, due_day, limit_amount, created_by, updated_by) VALUES ($1::uuid, $2, $3, $4, $5::uuid, $5::uuid)",
		accountID, 0, 15, 100000, userID,
	)
	assert.Error(t, err, "closing_day=0 must be rejected")

	// day=32 must be rejected.
	_, err = db.ExecContext(ctx,
		"INSERT INTO credit_card_settings (account_id, closing_day, due_day, limit_amount, created_by, updated_by) VALUES ($1::uuid, $2, $3, $4, $5::uuid, $5::uuid)",
		accountID, 32, 15, 100000, userID,
	)
	assert.Error(t, err, "closing_day=32 must be rejected")

	// Boundary values 1 and 31 must be accepted.
	_, err = db.ExecContext(ctx,
		"INSERT INTO credit_card_settings (account_id, closing_day, due_day, limit_amount, created_by, updated_by) VALUES ($1::uuid, $2, $3, $4, $5::uuid, $5::uuid)",
		accountID, 1, 15, 100000, userID,
	)
	assert.NoError(t, err, "closing_day=1 must be accepted")
}

// TestCreditCardSettingsMigration_DueDayRange verifies AC4 + EC2: due_day must be
// between 1 and 31 inclusive.
func TestCreditCardSettingsMigration_DueDayRange(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	db := newTestDB(t, ctx)
	require.NoError(t, Migrate(ctx, db, usersMigrationsFS(t)))

	var userID, householdID, accountID string
	err := db.QueryRowContext(ctx,
		"INSERT INTO users (email, password_hash, display_name) VALUES ($1, $2, $3) RETURNING id::text",
		"dave@example.com", testPasswordHash, "Dave",
	).Scan(&userID)
	require.NoError(t, err)

	err = db.QueryRowContext(ctx,
		"INSERT INTO households (name, created_by, updated_by) VALUES ($1, $2::uuid, $2::uuid) RETURNING id::text",
		"Dave's Household", userID,
	).Scan(&householdID)
	require.NoError(t, err)

	err = db.QueryRowContext(ctx,
		"INSERT INTO accounts (household_id, name, account_type, currency_code, created_by, updated_by) VALUES ($1::uuid, $2, $3, $4, $5::uuid, $5::uuid) RETURNING id::text",
		householdID, "Amex", "CREDIT_CARD", "USD", userID,
	).Scan(&accountID)
	require.NoError(t, err)

	// due_day=0 must be rejected.
	_, err = db.ExecContext(ctx,
		"INSERT INTO credit_card_settings (account_id, closing_day, due_day, limit_amount, created_by, updated_by) VALUES ($1::uuid, $2, $3, $4, $5::uuid, $5::uuid)",
		accountID, 15, 0, 100000, userID,
	)
	assert.Error(t, err, "due_day=0 must be rejected")

	// due_day=32 must be rejected.
	_, err = db.ExecContext(ctx,
		"INSERT INTO credit_card_settings (account_id, closing_day, due_day, limit_amount, created_by, updated_by) VALUES ($1::uuid, $2, $3, $4, $5::uuid, $5::uuid)",
		accountID, 15, 32, 100000, userID,
	)
	assert.Error(t, err, "due_day=32 must be rejected")

	// Boundary values 1 and 31 must be accepted.
	_, err = db.ExecContext(ctx,
		"INSERT INTO credit_card_settings (account_id, closing_day, due_day, limit_amount, created_by, updated_by) VALUES ($1::uuid, $2, $3, $4, $5::uuid, $5::uuid)",
		accountID, 15, 31, 100000, userID,
	)
	assert.NoError(t, err, "due_day=31 must be accepted")
}

// TestCreditCardSettingsMigration_LimitAmountIsBigint verifies AC5 + EC4: limit_amount
// is stored as BIGINT (minor units) and accepts large values without precision loss.
func TestCreditCardSettingsMigration_LimitAmountIsBigint(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	db := newTestDB(t, ctx)
	require.NoError(t, Migrate(ctx, db, usersMigrationsFS(t)))

	var userID, householdID, accountID string
	err := db.QueryRowContext(ctx,
		"INSERT INTO users (email, password_hash, display_name) VALUES ($1, $2, $3) RETURNING id::text",
		"eve@example.com", testPasswordHash, "Eve",
	).Scan(&userID)
	require.NoError(t, err)

	err = db.QueryRowContext(ctx,
		"INSERT INTO households (name, created_by, updated_by) VALUES ($1, $2::uuid, $2::uuid) RETURNING id::text",
		"Eve's Household", userID,
	).Scan(&householdID)
	require.NoError(t, err)

	err = db.QueryRowContext(ctx,
		"INSERT INTO accounts (household_id, name, account_type, currency_code, created_by, updated_by) VALUES ($1::uuid, $2, $3, $4, $5::uuid, $5::uuid) RETURNING id::text",
		householdID, "Platinum", "CREDIT_CARD", "USD", userID,
	).Scan(&accountID)
	require.NoError(t, err)

	// Store a large limit: $50,000.00 = 5_000_000 cents.
	largeLimit := int64(5_000_000)
	var storedLimit int64
	err = db.QueryRowContext(ctx,
		`INSERT INTO credit_card_settings (account_id, closing_day, due_day, limit_amount, created_by, updated_by)
		 VALUES ($1::uuid, $2, $3, $4, $5::uuid, $5::uuid) RETURNING limit_amount`,
		accountID, 20, 28, largeLimit, userID,
	).Scan(&storedLimit)

	require.NoError(t, err)
	assert.Equal(t, largeLimit, storedLimit, "BIGINT limit_amount must store and return large values exactly")
}

// TestCreditCardSettingsMigration_RollbackRemovesTable verifies AC6: rolling back the
// credit_card_settings migration drops the table cleanly.
func TestCreditCardSettingsMigration_RollbackRemovesTable(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	db := newTestDB(t, ctx)
	sub := usersMigrationsFS(t)
	require.NoError(t, Migrate(ctx, db, sub))

	var exists bool
	err := db.QueryRowContext(ctx,
		"SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'credit_card_settings')",
	).Scan(&exists)
	require.NoError(t, err)
	require.True(t, exists, "credit_card_settings table must exist after Up migration")

	provider, err := goose.NewProvider(goose.DialectPostgres, db, sub,
		goose.WithLogger(goose.NopLogger()),
	)
	require.NoError(t, err)

	// Roll back only this migration (version 3 → 2).
	_, err = provider.DownTo(ctx, 20260304000002)
	require.NoError(t, err)

	err = db.QueryRowContext(ctx,
		"SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'credit_card_settings')",
	).Scan(&exists)
	require.NoError(t, err)
	assert.False(t, exists, "credit_card_settings table must be absent after rollback")
}
