//go:build integration

package database

import (
	"context"
	"testing"

	"github.com/pressly/goose/v3"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestHouseholdsMigration_DefaultsOnCreate verifies AC1: a newly created household has
// status = 'ACTIVE', version = 1, and non-null audit timestamps.
func TestHouseholdsMigration_DefaultsOnCreate(t *testing.T) {
	ctx := context.Background()
	db := newTestDB(t, ctx)
	require.NoError(t, Migrate(ctx, db, usersMigrationsFS(t)))

	var userID string
	err := db.QueryRowContext(ctx,
		"INSERT INTO users (email, password_hash, display_name) VALUES ($1, $2, $3) RETURNING id::text",
		"alice@example.com", testPasswordHash, "Alice",
	).Scan(&userID)
	require.NoError(t, err)

	var id, status string
	var version int
	var createdOK, updatedOK bool
	err = db.QueryRowContext(ctx,
		`INSERT INTO households (name, created_by, updated_by)
		 VALUES ($1, $2::uuid, $2::uuid)
		 RETURNING id::text, status, version,
		           created_at IS NOT NULL,
		           updated_at IS NOT NULL`,
		"Personal", userID,
	).Scan(&id, &status, &version, &createdOK, &updatedOK)

	require.NoError(t, err)
	assert.NotEmpty(t, id, "household id must be generated by the database")
	assert.Equal(t, "ACTIVE", status, "default status must be ACTIVE")
	assert.Equal(t, 1, version, "version must default to 1")
	assert.True(t, createdOK, "created_at must be set automatically")
	assert.True(t, updatedOK, "updated_at must be set automatically")
}

// TestHouseholdsMigration_MembershipRecordsFields verifies AC2: a membership row captures
// household_id, user_id, role, and invited_by correctly.
func TestHouseholdsMigration_MembershipRecordsFields(t *testing.T) {
	ctx := context.Background()
	db := newTestDB(t, ctx)
	require.NoError(t, Migrate(ctx, db, usersMigrationsFS(t)))

	var adminID, memberID, householdID string

	err := db.QueryRowContext(ctx,
		"INSERT INTO users (email, password_hash, display_name) VALUES ($1, $2, $3) RETURNING id::text",
		"admin@example.com", testPasswordHash, "Admin",
	).Scan(&adminID)
	require.NoError(t, err)

	err = db.QueryRowContext(ctx,
		"INSERT INTO users (email, password_hash, display_name) VALUES ($1, $2, $3) RETURNING id::text",
		"member@example.com", testPasswordHash, "Member",
	).Scan(&memberID)
	require.NoError(t, err)

	err = db.QueryRowContext(ctx,
		"INSERT INTO households (name, created_by, updated_by) VALUES ($1, $2::uuid, $2::uuid) RETURNING id::text",
		"Family", adminID,
	).Scan(&householdID)
	require.NoError(t, err)

	// Add the admin as ADMIN member (invited_by NULL — self-join on household creation).
	_, err = db.ExecContext(ctx,
		"INSERT INTO household_members (household_id, user_id, role) VALUES ($1::uuid, $2::uuid, 'ADMIN')",
		householdID, adminID,
	)
	require.NoError(t, err)

	// Add a regular member, invited by the admin.
	_, err = db.ExecContext(ctx,
		`INSERT INTO household_members (household_id, user_id, role, invited_by)
		 VALUES ($1::uuid, $2::uuid, 'MEMBER', $3::uuid)`,
		householdID, memberID, adminID,
	)
	require.NoError(t, err)

	// Verify the member record captures all fields.
	var gotHouseholdID, gotUserID, gotRole, gotInvitedBy string
	err = db.QueryRowContext(ctx,
		`SELECT household_id::text, user_id::text, role, invited_by::text
		 FROM household_members
		 WHERE household_id = $1::uuid AND user_id = $2::uuid`,
		householdID, memberID,
	).Scan(&gotHouseholdID, &gotUserID, &gotRole, &gotInvitedBy)

	require.NoError(t, err)
	assert.Equal(t, householdID, gotHouseholdID)
	assert.Equal(t, memberID, gotUserID)
	assert.Equal(t, "MEMBER", gotRole)
	assert.Equal(t, adminID, gotInvitedBy)
}

// TestHouseholdsMigration_RoleEnforcedByCheck verifies AC3: only 'ADMIN' and 'MEMBER'
// are valid role values — any other value must be rejected by the CHECK constraint.
func TestHouseholdsMigration_RoleEnforcedByCheck(t *testing.T) {
	ctx := context.Background()
	db := newTestDB(t, ctx)
	require.NoError(t, Migrate(ctx, db, usersMigrationsFS(t)))

	var userID, householdID string
	err := db.QueryRowContext(ctx,
		"INSERT INTO users (email, password_hash, display_name) VALUES ($1, $2, $3) RETURNING id::text",
		"owner@example.com", testPasswordHash, "Owner",
	).Scan(&userID)
	require.NoError(t, err)

	err = db.QueryRowContext(ctx,
		"INSERT INTO households (name, created_by, updated_by) VALUES ($1, $2::uuid, $2::uuid) RETURNING id::text",
		"Business", userID,
	).Scan(&householdID)
	require.NoError(t, err)

	_, err = db.ExecContext(ctx,
		"INSERT INTO household_members (household_id, user_id, role) VALUES ($1::uuid, $2::uuid, 'SUPERADMIN')",
		householdID, userID,
	)
	assert.Error(t, err, "role 'SUPERADMIN' must be rejected by CHECK constraint")
}

// TestHouseholdsMigration_SoftDeletedHouseholdExcluded verifies AC4: a soft-deleted
// household must not appear in queries that filter WHERE deleted_at IS NULL.
func TestHouseholdsMigration_SoftDeletedHouseholdExcluded(t *testing.T) {
	ctx := context.Background()
	db := newTestDB(t, ctx)
	require.NoError(t, Migrate(ctx, db, usersMigrationsFS(t)))

	var userID, householdID string
	err := db.QueryRowContext(ctx,
		"INSERT INTO users (email, password_hash, display_name) VALUES ($1, $2, $3) RETURNING id::text",
		"user@example.com", testPasswordHash, "User",
	).Scan(&userID)
	require.NoError(t, err)

	err = db.QueryRowContext(ctx,
		"INSERT INTO households (name, created_by, updated_by) VALUES ($1, $2::uuid, $2::uuid) RETURNING id::text",
		"ToDelete", userID,
	).Scan(&householdID)
	require.NoError(t, err)

	_, err = db.ExecContext(ctx,
		"UPDATE households SET deleted_at = NOW() WHERE id = $1::uuid",
		householdID,
	)
	require.NoError(t, err)

	var count int
	err = db.QueryRowContext(ctx,
		"SELECT COUNT(*) FROM households WHERE id = $1::uuid AND deleted_at IS NULL",
		householdID,
	).Scan(&count)
	require.NoError(t, err)
	assert.Equal(t, 0, count, "soft-deleted household must not appear in active queries")
}

// TestHouseholdsMigration_SoftDeletedMemberRetained verifies AC5: soft-deleting a
// membership record sets deleted_at but retains the row for audit purposes.
func TestHouseholdsMigration_SoftDeletedMemberRetained(t *testing.T) {
	ctx := context.Background()
	db := newTestDB(t, ctx)
	require.NoError(t, Migrate(ctx, db, usersMigrationsFS(t)))

	var userID, householdID string
	err := db.QueryRowContext(ctx,
		"INSERT INTO users (email, password_hash, display_name) VALUES ($1, $2, $3) RETURNING id::text",
		"member@example.com", testPasswordHash, "Member",
	).Scan(&userID)
	require.NoError(t, err)

	err = db.QueryRowContext(ctx,
		"INSERT INTO households (name, created_by, updated_by) VALUES ($1, $2::uuid, $2::uuid) RETURNING id::text",
		"Household", userID,
	).Scan(&householdID)
	require.NoError(t, err)

	_, err = db.ExecContext(ctx,
		"INSERT INTO household_members (household_id, user_id, role) VALUES ($1::uuid, $2::uuid, 'ADMIN')",
		householdID, userID,
	)
	require.NoError(t, err)

	_, err = db.ExecContext(ctx,
		"UPDATE household_members SET deleted_at = NOW() WHERE household_id = $1::uuid AND user_id = $2::uuid",
		householdID, userID,
	)
	require.NoError(t, err)

	// Row must still exist with deleted_at populated — retained for audit.
	var deletedAtOK bool
	err = db.QueryRowContext(ctx,
		`SELECT deleted_at IS NOT NULL
		 FROM household_members
		 WHERE household_id = $1::uuid AND user_id = $2::uuid`,
		householdID, userID,
	).Scan(&deletedAtOK)
	require.NoError(t, err)
	assert.True(t, deletedAtOK, "soft-deleted member must be retained with deleted_at set")
}

// TestHouseholdsMigration_RollbackRemovesBothTables verifies AC6: rolling back the
// household migration drops both tables and all associated constraints cleanly.
func TestHouseholdsMigration_RollbackRemovesBothTables(t *testing.T) {
	ctx := context.Background()
	db := newTestDB(t, ctx)
	sub := usersMigrationsFS(t)
	require.NoError(t, Migrate(ctx, db, sub))

	for _, table := range []string{"households", "household_members"} {
		var exists bool
		err := db.QueryRowContext(ctx,
			"SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = $1)",
			table,
		).Scan(&exists)
		require.NoError(t, err)
		require.Truef(t, exists, "%s must exist after Up migration", table)
	}

	provider, err := goose.NewProvider(goose.DialectPostgres, db, sub,
		goose.WithLogger(goose.NopLogger()),
	)
	require.NoError(t, err)

	_, err = provider.DownTo(ctx, 0)
	require.NoError(t, err)

	for _, table := range []string{"households", "household_members"} {
		var exists bool
		err := db.QueryRowContext(ctx,
			"SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = $1)",
			table,
		).Scan(&exists)
		require.NoError(t, err)
		assert.Falsef(t, exists, "%s must be absent after rollback", table)
	}
}
