//go:build integration

package database

import (
	"context"
	"io/fs"
	"strings"
	"testing"

	"github.com/pressly/goose/v3"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	pfmdb "github.com/zambone/pfm-go/db"
)

// usersMigrationsFS returns the sub-filesystem used by the real application startup.
// It mirrors the fs.Sub call in cmd/pfm/main.go's run().
func usersMigrationsFS(t *testing.T) fs.FS {
	t.Helper()
	sub, err := fs.Sub(pfmdb.Migrations, "migrations")
	require.NoError(t, err)
	return sub
}

// testPasswordHash is a 128-character string satisfying the Argon2id minimum column width.
var testPasswordHash = strings.Repeat("x", 128)

// TestUsersMigration_UUIDGeneratedByDB verifies AC1: the database generates a UUIDv7
// when a user is inserted without an explicit id.
func TestUsersMigration_UUIDGeneratedByDB(t *testing.T) {
	ctx := context.Background()
	db := newTestDB(t, ctx)
	require.NoError(t, Migrate(ctx, db, usersMigrationsFS(t)))

	var id string
	err := db.QueryRowContext(ctx,
		"INSERT INTO users (email, password_hash, display_name) VALUES ($1, $2, $3) RETURNING id::text",
		"alice@example.com", testPasswordHash, "Alice",
	).Scan(&id)

	require.NoError(t, err)
	assert.NotEmpty(t, id, "id must be generated by the database")
	assert.Len(t, id, 36, "generated id must be a UUID (36 chars with dashes)")
}

// TestUsersMigration_EmailUniquenessEnforced verifies AC2: inserting two active users
// with the same email (case-insensitive) is rejected by the database.
func TestUsersMigration_EmailUniquenessEnforced(t *testing.T) {
	ctx := context.Background()
	db := newTestDB(t, ctx)
	require.NoError(t, Migrate(ctx, db, usersMigrationsFS(t)))

	_, err := db.ExecContext(ctx,
		"INSERT INTO users (email, password_hash, display_name) VALUES ($1, $2, $3)",
		"bob@example.com", testPasswordHash, "Bob",
	)
	require.NoError(t, err)

	// Same email with different case — must be rejected by the partial unique index.
	_, err = db.ExecContext(ctx,
		"INSERT INTO users (email, password_hash, display_name) VALUES ($1, $2, $3)",
		"BOB@example.com", testPasswordHash, "Bob Duplicate",
	)
	assert.Error(t, err, "duplicate email (case-insensitive) must be rejected")
}

// TestUsersMigration_SoftDeleteAllowsEmailReuse verifies AC3: after a user is soft-deleted,
// the same email can be registered again.
func TestUsersMigration_SoftDeleteAllowsEmailReuse(t *testing.T) {
	ctx := context.Background()
	db := newTestDB(t, ctx)
	require.NoError(t, Migrate(ctx, db, usersMigrationsFS(t)))

	_, err := db.ExecContext(ctx,
		"INSERT INTO users (email, password_hash, display_name) VALUES ($1, $2, $3)",
		"carol@example.com", testPasswordHash, "Carol",
	)
	require.NoError(t, err)

	// Soft-delete the user — partial index no longer covers this row.
	_, err = db.ExecContext(ctx,
		"UPDATE users SET deleted_at = NOW() WHERE email = $1",
		"carol@example.com",
	)
	require.NoError(t, err)

	// Re-registration with the same email must succeed.
	_, err = db.ExecContext(ctx,
		"INSERT INTO users (email, password_hash, display_name) VALUES ($1, $2, $3)",
		"carol@example.com", testPasswordHash, "Carol Re-registered",
	)
	assert.NoError(t, err, "email must be reusable after soft-delete")
}

// TestUsersMigration_TimestampsSetOnCreate verifies AC4: created_at and updated_at are
// populated automatically when a row is inserted.
func TestUsersMigration_TimestampsSetOnCreate(t *testing.T) {
	ctx := context.Background()
	db := newTestDB(t, ctx)
	require.NoError(t, Migrate(ctx, db, usersMigrationsFS(t)))

	_, err := db.ExecContext(ctx,
		"INSERT INTO users (email, password_hash, display_name) VALUES ($1, $2, $3)",
		"dave@example.com", testPasswordHash, "Dave",
	)
	require.NoError(t, err)

	var createdOK, updatedOK bool
	err = db.QueryRowContext(ctx,
		"SELECT created_at IS NOT NULL, updated_at IS NOT NULL FROM users WHERE email = $1",
		"dave@example.com",
	).Scan(&createdOK, &updatedOK)
	require.NoError(t, err)
	assert.True(t, createdOK, "created_at must be set automatically on insert")
	assert.True(t, updatedOK, "updated_at must be set automatically on insert")
}

// TestUsersMigration_CreatedAtImmutableOnUpdate verifies AC5: updating a row must not
// change created_at — only updated_at is allowed to change.
func TestUsersMigration_CreatedAtImmutableOnUpdate(t *testing.T) {
	ctx := context.Background()
	db := newTestDB(t, ctx)
	require.NoError(t, Migrate(ctx, db, usersMigrationsFS(t)))

	_, err := db.ExecContext(ctx,
		"INSERT INTO users (email, password_hash, display_name) VALUES ($1, $2, $3)",
		"eve@example.com", testPasswordHash, "Eve",
	)
	require.NoError(t, err)

	var createdBefore string
	err = db.QueryRowContext(ctx,
		"SELECT created_at::text FROM users WHERE email = $1",
		"eve@example.com",
	).Scan(&createdBefore)
	require.NoError(t, err)

	_, err = db.ExecContext(ctx,
		"UPDATE users SET display_name = $1, updated_at = NOW() WHERE email = $2",
		"Eve Updated", "eve@example.com",
	)
	require.NoError(t, err)

	var createdAfter string
	err = db.QueryRowContext(ctx,
		"SELECT created_at::text FROM users WHERE email = $1",
		"eve@example.com",
	).Scan(&createdAfter)
	require.NoError(t, err)

	assert.Equal(t, createdBefore, createdAfter, "created_at must not change on UPDATE")
}

// TestUsersMigration_VersionStartsAtOne verifies AC6: every new row has version = 1.
func TestUsersMigration_VersionStartsAtOne(t *testing.T) {
	ctx := context.Background()
	db := newTestDB(t, ctx)
	require.NoError(t, Migrate(ctx, db, usersMigrationsFS(t)))

	_, err := db.ExecContext(ctx,
		"INSERT INTO users (email, password_hash, display_name) VALUES ($1, $2, $3)",
		"frank@example.com", testPasswordHash, "Frank",
	)
	require.NoError(t, err)

	var version int
	err = db.QueryRowContext(ctx,
		"SELECT version FROM users WHERE email = $1",
		"frank@example.com",
	).Scan(&version)
	require.NoError(t, err)
	assert.Equal(t, 1, version, "version must default to 1 on insert")
}

// TestUsersMigration_RollbackRemovesTable verifies AC7: running the Down migration
// drops the users table and all its indexes cleanly.
func TestUsersMigration_RollbackRemovesTable(t *testing.T) {
	ctx := context.Background()
	db := newTestDB(t, ctx)
	sub := usersMigrationsFS(t)

	require.NoError(t, Migrate(ctx, db, sub))

	var exists bool
	err := db.QueryRowContext(ctx,
		"SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'users')",
	).Scan(&exists)
	require.NoError(t, err)
	require.True(t, exists, "users table must exist after Up")

	// Roll back all migrations using the goose Provider directly.
	provider, err := goose.NewProvider(goose.DialectPostgres, db, sub,
		goose.WithLogger(goose.NopLogger()),
	)
	require.NoError(t, err)

	_, err = provider.DownTo(ctx, 0)
	require.NoError(t, err)

	err = db.QueryRowContext(ctx,
		"SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'users')",
	).Scan(&exists)
	require.NoError(t, err)
	assert.False(t, exists, "users table must be absent after rollback")
}
