// Package api embeds the generated OpenAPI specification for the PFM-Go REST API.
package api

import _ "embed"

// SwaggerYAML is the OpenAPI 2.0 specification generated by swag from handler annotations.
// Regenerate with: make generate
//
//go:embed swagger.yaml
var SwaggerYAML []byte
